import os
from pathlib import Path

import dotenv

dotenv.load_dotenv()

YOUTUBE_API_KEY = os.environ["FARMER_LOCAL_YOUTUBE_API_KEY"]
YOUTUBE_CHANNEL_ID = os.environ["FARMER_LOCAL_YOUTUBE_CHANNEL_ID"]
YOUTUBE_CHANNEL_NAME = os.environ["FARMER_LOCAL_YOUTUBE_CHANNEL_NAME"]

WOLT_NAME = os.environ["FARMER_LOCAL_WOLT_NAME"]

MODAL_APP_NAME = os.environ["FARMER_LOCAL_MODAL_APP_NAME"]
MODAL_PROCESS_FUNCTION_NAME = os.environ["FARMER_LOCAL_MODAL_PROCESS_FUNCTION_NAME"]
MODAL_PROCESS_DOWNLOAD_NAME = os.environ["FARMER_LOCAL_MODAL_DOWNLOAD_FUNCTION_NAME"]

DATABASE_CONNECTION_STRING = os.environ["FARMER_LOCAL_DATABASE_CONNECTION_STRING"]

LOGGING_PATH_FOLDER = os.getenv("FARMER_LOCAL_LOGGING_PATH_FOLDER", str(Path().absolute()))

DISCORD_CHANNEL = int(os.environ["FARMER_LOCAL_DISCORD_CHANNEL"])
DISCORD_BOT_ID = os.environ["FARMER_LOCAL_DISCORD_BOT_ID"]
